export const genders = [
  { label: 'Male', value: 'male' },
  { label: 'Female', value: 'female' },
  { label: 'Non-Binary', value: 'non-binary' },
];

export const sports = [
  { value: 'american-football', label: 'American Football' },
  { value: 'aquatics', label: 'Aquatics' },
  { value: 'archery', label: 'Archery' },
  { value: 'automobile-racing', label: 'Automobile Racing' },
  { value: 'badminton', label: 'Badminton' },
  { value: 'baseball', label: 'Baseball' },
  { value: 'basketball', label: 'Basketball' },
  { value: 'beach-volleyball', label: 'Beach Volleyball' },
  { value: 'bobsleigh', label: 'Bobsleigh' },
  { value: 'body-building', label: 'Body Building' },
  { value: 'boxing', label: 'Boxing' },
  { value: 'cricket', label: 'Cricket' },
  { value: 'cross-country-running', label: 'Cross Country Running' },
  { value: 'cross-country-skiing', label: 'Cross Country Skiing' },
  { value: 'curling', label: 'Curling' },
  { value: 'cycling', label: 'Cycling' },
  { value: 'darts', label: 'Darts' },
  { value: 'decathlon', label: 'Decathlon' },
  { value: 'down-hill-skiing', label: 'Down Hill Skiing' },
  { value: 'equestrianism', label: 'Equestrianism' },
  { value: 'fencing', label: 'Fencing' },
  { value: 'field-hockey', label: 'Field Hockey' },
  { value: 'figure-skating', label: 'Figure Skating' },
  { value: 'golf', label: 'Golf' },
  { value: 'gymnastics', label: 'Gymnastics' },
  { value: 'ice-hockey', label: 'Ice Hockey' },
  { value: 'martial-arts', label: 'Martial Arts' },
  { value: 'mixed-martial-arts', label: 'Mixed Martial Arts' },
  { value: 'modern-pentathlon', label: 'Modern Pentathlon' },
  { value: 'motorcycle-racing', label: 'Motorcycle Racing' },
  { value: 'netball', label: 'Netball' },
  { value: 'polo', label: 'Polo' },
  { value: 'racquetball', label: 'Racquetball' },
  { value: 'rowing', label: 'Rowing' },
  { value: 'rugby', label: 'Rugby' },
  { value: 'sailing', label: 'Sailing' },
  { value: 'shooting', label: 'Shooting' },
  { value: 'skateboarding', label: 'Skateboarding' },
  { value: 'skeet-shooting', label: 'Skeet Shooting' },
  { value: 'skeleton', label: 'Skeleton' },
  { value: 'snow-boarding', label: 'Snow Boarding' },
  { value: 'soccer-football', label: 'Soccer (Football)' },
  { value: 'softball', label: 'Softball' },
  { value: 'squash', label: 'Squash' },
  { value: 'surfing', label: 'Surfing' },
  { value: 'swimming', label: 'Swimming' },
  { value: 'tennis', label: 'Tennis' },
  { value: 'track-and field', label: 'Track and Field' },
  { value: 'esports', label: 'eSports' },
];
